// Birth Card (BC) and Planetary Ruling Card (PRC) lookup by birthday
// Format: { month: { day: { bc: "Birth Card", prc: "Planetary Ruling Card" } } }

export const DESTINY_CARDS = {
  // JANUARY
  1: {
    1: { bc: "A♠", prc: "2♠" },
    2: { bc: "2♠", prc: "4♠" },
    3: { bc: "3♠", prc: "6♠" },
    4: { bc: "4♠", prc: "8♠" },
    5: { bc: "5♠", prc: "10♠" },
    6: { bc: "6♠", prc: "Q♠" },
    7: { bc: "7♠", prc: "A♥" },
    8: { bc: "8♠", prc: "3♥" },
    9: { bc: "9♠", prc: "5♥" },
    10: { bc: "10♠", prc: "7♥" },
    11: { bc: "J♠", prc: "9♥" },
    12: { bc: "Q♠", prc: "J♥" },
    13: { bc: "K♠", prc: "K♥" },
    14: { bc: "A♥", prc: "2♥" },
    15: { bc: "2♥", prc: "4♥" },
    16: { bc: "3♥", prc: "6♥" },
    17: { bc: "4♥", prc: "8♥" },
    18: { bc: "5♥", prc: "10♥" },
    19: { bc: "6♥", prc: "Q♥" },
    20: { bc: "7♥", prc: "A♣" },
    21: { bc: "8♥", prc: "3♣" },
    22: { bc: "9♥", prc: "5♣" },
    23: { bc: "10♥", prc: "7♣" },
    24: { bc: "J♥", prc: "9♣" },
    25: { bc: "Q♥", prc: "J♣" },
    26: { bc: "K♥", prc: "K♣" },
    27: { bc: "A♣", prc: "2♣" },
    28: { bc: "2♣", prc: "4♣" },
    29: { bc: "3♣", prc: "6♣" },
    30: { bc: "4♣", prc: "8♣" },
    31: { bc: "5♣", prc: "10♣" }
  },
  // FEBRUARY
  2: {
    1: { bc: "6♣", prc: "Q♣" },
    2: { bc: "7♣", prc: "A♦" },
    3: { bc: "8♣", prc: "3♦" },
    4: { bc: "9♣", prc: "5♦" },
    5: { bc: "10♣", prc: "7♦" },
    6: { bc: "J♣", prc: "9♦" },
    7: { bc: "Q♣", prc: "J♦" },
    8: { bc: "K♣", prc: "K♦" },
    9: { bc: "A♦", prc: "2♦" },
    10: { bc: "2♦", prc: "4♦" },
    11: { bc: "3♦", prc: "6♦" },
    12: { bc: "4♦", prc: "8♦" },
    13: { bc: "5♦", prc: "10♦" },
    14: { bc: "6♦", prc: "Q♦" },
    15: { bc: "7♦", prc: "A♠" },
    16: { bc: "8♦", prc: "3♠" },
    17: { bc: "9♦", prc: "5♠" },
    18: { bc: "10♦", prc: "7♠" },
    19: { bc: "J♦", prc: "9♠" },
    20: { bc: "Q♦", prc: "J♠" },
    21: { bc: "K♦", prc: "K♠" },
    22: { bc: "A♠", prc: "A♠" },
    23: { bc: "2♠", prc: "2♠" },
    24: { bc: "3♠", prc: "3♠" },
    25: { bc: "4♠", prc: "4♠" },
    26: { bc: "5♠", prc: "5♠" },
    27: { bc: "6♠", prc: "6♠" },
    28: { bc: "7♠", prc: "7♠" },
    29: { bc: "8♠", prc: "8♠" }
  },
  // MARCH
  3: {
    1: { bc: "9♠", prc: "9♠" },
    2: { bc: "10♠", prc: "10♠" },
    3: { bc: "J♠", prc: "J♠" },
    4: { bc: "Q♠", prc: "Q♠" },
    5: { bc: "K♠", prc: "K♠" },
    6: { bc: "A♥", prc: "A♥" },
    7: { bc: "2♥", prc: "2♥" },
    8: { bc: "3♥", prc: "3♥" },
    9: { bc: "4♥", prc: "4♥" },
    10: { bc: "5♥", prc: "5♥" },
    11: { bc: "6♥", prc: "6♥" },
    12: { bc: "7♥", prc: "7♥" },
    13: { bc: "8♥", prc: "8♥" },
    14: { bc: "9♥", prc: "9♥" },
    15: { bc: "10♥", prc: "10♥" },
    16: { bc: "J♥", prc: "J♥" },
    17: { bc: "Q♥", prc: "Q♥" },
    18: { bc: "K♥", prc: "K♥" },
    19: { bc: "A♣", prc: "A♣" },
    20: { bc: "2♣", prc: "2♣" },
    21: { bc: "3♣", prc: "3♣" },
    22: { bc: "4♣", prc: "4♣" },
    23: { bc: "5♣", prc: "5♣" },
    24: { bc: "6♣", prc: "6♣" },
    25: { bc: "7♣", prc: "7♣" },
    26: { bc: "8♣", prc: "8♣" },
    27: { bc: "9♣", prc: "9♣" },
    28: { bc: "10♣", prc: "10♣" },
    29: { bc: "J♣", prc: "J♣" },
    30: { bc: "Q♣", prc: "Q♣" },
    31: { bc: "K♣", prc: "K♣" }
  },
  // APRIL
  4: {
    1: { bc: "A♦", prc: "A♦" },
    2: { bc: "2♦", prc: "2♦" },
    3: { bc: "3♦", prc: "3♦" },
    4: { bc: "4♦", prc: "4♦" },
    5: { bc: "5♦", prc: "5♦" },
    6: { bc: "6♦", prc: "6♦" },
    7: { bc: "7♦", prc: "7♦" },
    8: { bc: "8♦", prc: "8♦" },
    9: { bc: "9♦", prc: "9♦" },
    10: { bc: "10♦", prc: "10♦" },
    11: { bc: "J♦", prc: "J♦" },
    12: { bc: "Q♦", prc: "Q♦" },
    13: { bc: "K♦", prc: "K♦" },
    14: { bc: "A♠", prc: "3♠" },
    15: { bc: "2♠", prc: "5♠" },
    16: { bc: "3♠", prc: "7♠" },
    17: { bc: "4♠", prc: "9♠" },
    18: { bc: "5♠", prc: "J♠" },
    19: { bc: "6♠", prc: "K♠" },
    20: { bc: "7♠", prc: "2♥" },
    21: { bc: "8♠", prc: "4♥" },
    22: { bc: "9♠", prc: "6♥" },
    23: { bc: "10♠", prc: "8♥" },
    24: { bc: "J♠", prc: "10♥" },
    25: { bc: "Q♠", prc: "Q♥" },
    26: { bc: "K♠", prc: "A♣" },
    27: { bc: "A♥", prc: "3♣" },
    28: { bc: "2♥", prc: "5♣" },
    29: { bc: "3♥", prc: "7♣" },
    30: { bc: "4♥", prc: "9♣" }
  },
  // MAY
  5: {
    1: { bc: "5♥", prc: "J♣" },
    2: { bc: "6♥", prc: "K♣" },
    3: { bc: "7♥", prc: "2♦" },
    4: { bc: "8♥", prc: "4♦" },
    5: { bc: "9♥", prc: "6♦" },
    6: { bc: "10♥", prc: "8♦" },
    7: { bc: "J♥", prc: "10♦" },
    8: { bc: "Q♥", prc: "Q♦" },
    9: { bc: "K♥", prc: "A♠" },
    10: { bc: "A♣", prc: "3♠" },
    11: { bc: "2♣", prc: "5♠" },
    12: { bc: "3♣", prc: "7♠" },
    13: { bc: "4♣", prc: "9♠" },
    14: { bc: "5♣", prc: "J♠" },
    15: { bc: "6♣", prc: "K♠" },
    16: { bc: "7♣", prc: "2♥" },
    17: { bc: "8♣", prc: "4♥" },
    18: { bc: "9♣", prc: "6♥" },
    19: { bc: "10♣", prc: "8♥" },
    20: { bc: "J♣", prc: "10♥" },
    21: { bc: "Q♣", prc: "Q♥" },
    22: { bc: "K♣", prc: "A♣" },
    23: { bc: "A♦", prc: "3♣" },
    24: { bc: "2♦", prc: "5♣" },
    25: { bc: "3♦", prc: "7♣" },
    26: { bc: "4♦", prc: "9♣" },
    27: { bc: "5♦", prc: "J♣" },
    28: { bc: "6♦", prc: "K♣" },
    29: { bc: "7♦", prc: "2♦" },
    30: { bc: "8♦", prc: "4♦" },
    31: { bc: "9♦", prc: "6♦" }
  },
  // JUNE
  6: {
    1: { bc: "10♦", prc: "8♦" },
    2: { bc: "J♦", prc: "10♦" },
    3: { bc: "Q♦", prc: "Q♦" },
    4: { bc: "K♦", prc: "A♠" },
    5: { bc: "A♠", prc: "4♠" },
    6: { bc: "2♠", prc: "6♠" },
    7: { bc: "3♠", prc: "8♠" },
    8: { bc: "4♠", prc: "10♠" },
    9: { bc: "5♠", prc: "Q♠" },
    10: { bc: "6♠", prc: "A♥" },
    11: { bc: "7♠", prc: "3♥" },
    12: { bc: "8♠", prc: "5♥" },
    13: { bc: "9♠", prc: "7♥" },
    14: { bc: "10♠", prc: "9♥" },
    15: { bc: "J♠", prc: "J♥" },
    16: { bc: "Q♠", prc: "K♥" },
    17: { bc: "K♠", prc: "2♣" },
    18: { bc: "A♥", prc: "4♣" },
    19: { bc: "2♥", prc: "6♣" },
    20: { bc: "3♥", prc: "8♣" },
    21: { bc: "4♥", prc: "10♣" },
    22: { bc: "5♥", prc: "Q♣" },
    23: { bc: "6♥", prc: "A♦" },
    24: { bc: "7♥", prc: "3♦" },
    25: { bc: "8♥", prc: "5♦" },
    26: { bc: "9♥", prc: "7♦" },
    27: { bc: "10♥", prc: "9♦" },
    28: { bc: "J♥", prc: "J♦" },
    29: { bc: "Q♥", prc: "K♦" },
    30: { bc: "K♥", prc: "2♠" }
  },
  // JULY
  7: {
    1: { bc: "A♠", prc: "3♦" },
    2: { bc: "K♦", prc: "K♥" },
    3: { bc: "Q♦", prc: "A♦" },
    4: { bc: "J♦", prc: "K♠" },
    5: { bc: "10♦", prc: "10♥" },
    6: { bc: "9♦", prc: "J♠" },
    7: { bc: "8♦", prc: "10♠" },
    8: { bc: "7♦", prc: "7♥" },
    9: { bc: "6♦", prc: "8♠" },
    10: { bc: "5♦", prc: "7♠" },
    11: { bc: "4♦", prc: "4♥" },
    12: { bc: "3♦", prc: "5♠" },
    13: { bc: "A♦", prc: "A♥" },
    14: { bc: "K♠", prc: "2♠" },
    15: { bc: "Q♠", prc: "A♠" },
    16: { bc: "J♠", prc: "Q♠" },
    17: { bc: "J♠", prc: "Q♠" },
    18: { bc: "10♠", prc: "Q♥" },
    19: { bc: "9♠", prc: "J♥" },
    20: { bc: "8♠", prc: "J♠" },
    21: { bc: "7♠", prc: "9♥" },
    22: { bc: "6♠", prc: "8♥" },
    23: { bc: "5♠", prc: "10♠", prc_alt: "5♠" },
    24: { bc: "4♠", prc: "4♠" },
    25: { bc: "3♠", prc: "3♠" },
    26: { bc: "2♠", prc: "2♠" },
    27: { bc: "A♠", prc: "A♠" },
    28: { bc: "K♥", prc: "K♥" },
    29: { bc: "Q♥", prc: "Q♥" },
    30: { bc: "J♥", prc: "J♥" },
    31: { bc: "10♥", prc: "10♥" }
  },
  // AUGUST
  8: {
    1: { bc: "Q♦", prc: "Q♦" },
    2: { bc: "J♦", prc: "J♦" },
    3: { bc: "10♦", prc: "10♦" },
    4: { bc: "9♦", prc: "9♦" },
    5: { bc: "8♦", prc: "8♦" },
    6: { bc: "7♦", prc: "7♦" },
    7: { bc: "6♦", prc: "6♦" },
    8: { bc: "5♦", prc: "5♦" },
    9: { bc: "4♦", prc: "4♦" },
    10: { bc: "3♦", prc: "3♦" },
    11: { bc: "2♦", prc: "2♦" },
    12: { bc: "A♦", prc: "A♦" },
    13: { bc: "K♠", prc: "K♠" },
    14: { bc: "Q♠", prc: "Q♠" },
    15: { bc: "J♠", prc: "J♠" },
    16: { bc: "10♠", prc: "10♠" },
    17: { bc: "9♠", prc: "9♠" },
    18: { bc: "8♠", prc: "8♠" },
    19: { bc: "7♠", prc: "7♠" },
    20: { bc: "6♠", prc: "6♠" },
    21: { bc: "5♠", prc: "5♠" },
    22: { bc: "4♠", prc: "4♠", prc_alt: "2♦" },
    23: { bc: "3♠", prc: "3♠", prc_alt: "3♠" },
    24: { bc: "2♠", prc: "K♠" },
    25: { bc: "A♠", prc: "Q♠" },
    26: { bc: "K♥", prc: "K♦" },
    27: { bc: "Q♥", prc: "Q♦" },
    28: { bc: "J♥", prc: "9♠" },
    29: { bc: "10♥", prc: "10♦" },
    30: { bc: "9♥", prc: "7♠" },
    31: { bc: "8♥", prc: "6♠" }
  },
  // SEPTEMBER
  9: {
    1: { bc: "10♦", prc: "8♠" },
    2: { bc: "9♦", prc: "7♠" },
    3: { bc: "8♦", prc: "K♠" },
    4: { bc: "7♦", prc: "5♠" },
    5: { bc: "6♦", prc: "4♠" },
    6: { bc: "5♦", prc: "Q♠" },
    7: { bc: "4♦", prc: "2♠" },
    8: { bc: "3♦", prc: "A♠" },
    9: { bc: "2♦", prc: "J♠" },
    10: { bc: "A♦", prc: "Q♦" },
    11: { bc: "K♠", prc: "J♦" },
    12: { bc: "Q♠", prc: "10♠" },
    13: { bc: "J♠", prc: "9♦" },
    14: { bc: "10♠", prc: "8♦" },
    15: { bc: "9♠", prc: "9♠" },
    16: { bc: "8♠", prc: "6♦" },
    17: { bc: "7♠", prc: "5♦" },
    18: { bc: "6♠", prc: "6♠" },
    19: { bc: "5♠", prc: "3♦" },
    20: { bc: "4♠", prc: "2♦" },
    21: { bc: "3♠", prc: "3♠" },
    22: { bc: "2♠", prc: "K♠", prc_alt: "J♦" },
    23: { bc: "A♠", prc: "Q♠", prc_alt: "10♠" },
    24: { bc: "K♥", prc: "6♥" },
    25: { bc: "Q♥", prc: "8♦" },
    26: { bc: "J♥", prc: "9♠" },
    27: { bc: "10♥", prc: "8♠" },
    28: { bc: "9♥", prc: "5♦" },
    29: { bc: "8♥", prc: "6♠" },
    30: { bc: "7♥", prc: "5♠" }
  },
  // OCTOBER
  10: {
    1: { bc: "8♦", prc: "3♥" },
    2: { bc: "7♦", prc: "J♥" },
    3: { bc: "6♦", prc: "10♥" },
    4: { bc: "5♦", prc: "J♠" },
    5: { bc: "4♦", prc: "8♥" },
    6: { bc: "3♦", prc: "7♥" },
    7: { bc: "2♦", prc: "8♠" },
    8: { bc: "A♦", prc: "5♥" },
    9: { bc: "K♠", prc: "4♥" },
    10: { bc: "Q♠", prc: "5♠" },
    11: { bc: "J♠", prc: "7♠" },
    12: { bc: "10♠", prc: "K♠" },
    13: { bc: "9♠", prc: "2♥" },
    14: { bc: "8♠", prc: "4♠" },
    15: { bc: "7♠", prc: "Q♠" },
    16: { bc: "6♠", prc: "Q♥" },
    17: { bc: "5♠", prc: "A♠" },
    18: { bc: "4♠", prc: "J♠" },
    19: { bc: "3♠", prc: "9♥" },
    20: { bc: "2♠", prc: "J♦" },
    21: { bc: "A♠", prc: "10♠" },
    22: { bc: "K♥", prc: "6♥" },
    23: { bc: "Q♥", prc: "8♦", prc_alt: "K♠ & 5♠" },
    24: { bc: "J♥", prc: "9♥", prc_alt: "2♥ & 2♦" },
    25: { bc: "10♥", prc: "A♥ & 3♠" },
    26: { bc: "9♥", prc: "Q♠ & K♠" },
    27: { bc: "8♥", prc: "Q♥ & A♠" },
    28: { bc: "7♥", prc: "J♥ & K♠" },
    29: { bc: "6♥", prc: "J♠ & 10♦" },
    30: { bc: "5♥", prc: "9♥ & 9♦" },
    31: { bc: "4♥", prc: "8♥ & 8♦" }
  },
  // NOVEMBER
  11: {
    1: { bc: "6♦", prc: "10♦ & 5♥" },
    2: { bc: "5♦", prc: "9♦ & 4♥" },
    3: { bc: "4♦", prc: "6♠ & K♠" },
    4: { bc: "3♦", prc: "7♦ & 2♥" },
    5: { bc: "2♦", prc: "6♦ & A♥" },
    6: { bc: "A♦", prc: "3♠ & Q♠" },
    7: { bc: "K♠", prc: "4♦ & Q♥" },
    8: { bc: "Q♠", prc: "3♦ & J♥" },
    9: { bc: "J♠", prc: "2♠ & 2♠" },
    10: { bc: "10♠", prc: "3♥ & 3♦" },
    11: { bc: "9♠", prc: "K♥ & J♠" },
    12: { bc: "8♠", prc: "10♥ & Q♦" },
    13: { bc: "7♠", prc: "J♠ & J♦" },
    14: { bc: "6♠", prc: "10♠ & Q♠" },
    15: { bc: "5♠", prc: "7♥ & 9♠" },
    16: { bc: "4♠", prc: "8♠ & 8♠" },
    17: { bc: "3♠", prc: "7♠ & 7♠" },
    18: { bc: "2♠", prc: "4♥ & 6♠" },
    19: { bc: "A♠", prc: "5♠ & 5♠" },
    20: { bc: "K♥", prc: "4♠ & 4♠" },
    21: { bc: "Q♥", prc: "K♠ & 5♠" },
    22: { bc: "J♥", prc: "2♥ & 2♦" },
    23: { bc: "10♥", prc: "A♦" },
    24: { bc: "9♥", prc: "J♠" },
    25: { bc: "8♥", prc: "10♠" },
    26: { bc: "7♥", prc: "9♠" },
    27: { bc: "6♥", prc: "8♠" },
    28: { bc: "5♥", prc: "7♠" },
    29: { bc: "4♥", prc: "6♠" },
    30: { bc: "3♥", prc: "5♠" }
  },
  // DECEMBER
  12: {
    1: { bc: "4♦", prc: "6♠" },
    2: { bc: "3♦", prc: "5♠" },
    3: { bc: "2♦", prc: "4♠" },
    4: { bc: "A♦", prc: "3♠" },
    5: { bc: "K♠", prc: "2♠" },
    6: { bc: "Q♠", prc: "A♠" },
    7: { bc: "J♠", prc: "K♠" },
    8: { bc: "10♠", prc: "A♠" },
    9: { bc: "9♠", prc: "K♦" },
    10: { bc: "8♠", prc: "10♦" },
    11: { bc: "7♠", prc: "9♦" },
    12: { bc: "6♠", prc: "8♦" },
    13: { bc: "5♠", prc: "7♦" },
    14: { bc: "4♠", prc: "6♦" },
    15: { bc: "3♠", prc: "5♦" },
    16: { bc: "2♠", prc: "4♦" },
    17: { bc: "A♠", prc: "3♦" },
    18: { bc: "K♥", prc: "2♦" },
    19: { bc: "Q♥", prc: "3♥" },
    20: { bc: "J♥", prc: "K♥" },
    21: { bc: "10♥", prc: "A♦", prc_alt: "Q♦" },
    22: { bc: "9♥", prc: "J♦", prc_alt: "9♦" },
    23: { bc: "8♥", prc: "8♦" },
    24: { bc: "7♥", prc: "9♠" },
    25: { bc: "6♥", prc: "6♦" },
    26: { bc: "5♥", prc: "5♦" },
    27: { bc: "4♥", prc: "6♠" },
    28: { bc: "3♥", prc: "3♦" },
    29: { bc: "2♥", prc: "2♦" },
    30: { bc: "A♥", prc: "3♠" },
    31: { bc: "Joker", prc: "Joker" }
  }
};

/**
 * Get destiny cards (Birth Card and Planetary Ruling Card) from a date
 * @param {Date|string} birthDate - Date object or date string
 * @returns {{ birthCard: string, sunCard: string } | null}
 */
export function getDestinyCards(birthDate) {
  if (!birthDate) return null;
  
  const date = birthDate instanceof Date ? birthDate : new Date(birthDate);
  if (isNaN(date.getTime())) return null;
  
  const month = date.getMonth() + 1; // JS months are 0-indexed
  const day = date.getDate();
  
  const cards = DESTINY_CARDS[month]?.[day];
  if (!cards) return null;
  
  return {
    birthCard: cards.bc,
    sunCard: cards.prc
  };
}

/**
 * Format card with color styling info
 * @param {string} card - Card string like "A♠" or "K♥"
 * @returns {{ card: string, isRed: boolean }}
 */
export function getCardStyle(card) {
  if (!card) return { card: '', isRed: false };
  const isRed = card.includes('♥') || card.includes('♦');
  return { card, isRed };
}

// Card meanings for display
export const CARD_MEANINGS = {
  'A': 'New beginnings, individuality, leadership',
  '2': 'Partnership, balance, cooperation',
  '3': 'Creativity, expression, growth',
  '4': 'Stability, foundation, structure',
  '5': 'Change, adventure, freedom',
  '6': 'Harmony, responsibility, nurturing',
  '7': 'Spirituality, wisdom, introspection',
  '8': 'Power, abundance, success',
  '9': 'Completion, universal love, humanitarianism',
  '10': 'Achievement, fulfillment, mastery',
  'J': 'Youth, creativity, messenger',
  'Q': 'Intuition, nurturing, receptivity',
  'K': 'Authority, mastery, leadership',
  'Joker': 'Wild card, unlimited potential, cosmic consciousness'
};

export const SUIT_MEANINGS = {
  '♠': { name: 'Spades', meaning: 'Work, health, wisdom, transformation' },
  '♥': { name: 'Hearts', meaning: 'Love, relationships, emotions, family' },
  '♣': { name: 'Clubs', meaning: 'Knowledge, communication, mental pursuits' },
  '♦': { name: 'Diamonds', meaning: 'Values, finances, material world' }
};