export const GLOSSARY_TERMS = [
  // Platform
  { term: 'SaintAgent', short: 'The platform powering conscious collaboration, missions, and community.', long: 'SaintAgent is a next-generation social collaboration platform built for purpose-driven individuals. It combines project management, community networking, spiritual growth tools, and an internal economy powered by GGG tokens.', category: 'platform' },
  { term: 'Command Deck', short: 'Your personal dashboard and mission control center.', long: 'The Command Deck is the main landing page after login. It displays your key stats, upcoming meetings, active missions, synchronicity feed, and quick actions — all customizable via Simple, Advanced, or Custom view modes.', category: 'platform' },
  { term: 'SA Number', short: 'Unique SaintAgent identifier assigned to every member.', long: 'Each member receives a sequential SA number (e.g., SA-000042) upon completing onboarding. It serves as a permanent identity badge within the ecosystem.', category: 'platform' },
  { term: 'View Mode', short: 'Toggle between Simple, Advanced, or Custom layouts.', long: 'View Mode controls which cards and navigation items appear on your Command Deck and sidebar. Simple shows the essentials, Advanced shows everything, and Custom lets you pick exactly what you want.', category: 'platform' },
  { term: 'Creator Studio', short: 'Hub for managing offerings, content, and subscriptions.', long: 'The Creator Studio lets you create digital products, manage subscription tiers, publish content, and track earnings — all in one place.', category: 'platform' },
  { term: 'Side Panel', short: 'Contextual panel showing matches, meetings, and quick actions.', long: 'The Side Panel appears on the right side of the Command Deck, providing at-a-glance access to your matches, upcoming meetings, and GGG balance.', category: 'platform' },

  // Economy & GGG
  { term: 'GGG', short: 'Gaia Global Gold — the platform\'s internal token and reward currency.', long: 'GGG (Gaia Global Gold) is the native token of the SaintAgent ecosystem. It is earned through missions, feedback, community contributions, and marketplace activity. GGG can be spent on services, tipped to others, or staked for rewards.', category: 'economy' },
  { term: 'GGG Balance', short: 'Your current token holdings displayed on the Command Deck.', long: 'Your GGG Balance reflects all earned, spent, and received tokens. It updates in real-time and is visible in the wallet panel and side panel.', category: 'economy' },
  { term: 'Wallet', short: 'Secure storage and transaction hub for GGG tokens.', long: 'The Wallet manages your GGG holdings, transaction history, staking positions, and withdrawal requests. It supports both platform-native and crypto-bridge operations.', category: 'economy' },
  { term: 'Tip', short: 'Send GGG tokens directly to another member.', long: 'Tipping is a way to reward helpful content, great advice, or outstanding contributions. Tips are instant, peer-to-peer GGG transfers.', category: 'economy' },
  { term: 'Staking', short: 'Lock GGG tokens to earn yield and governance power.', long: 'Staking lets you lock GGG in pools to earn rewards over time. Staked tokens also grant voting power in governance decisions.', category: 'economy' },
  { term: 'G3DEX', short: 'The decentralized exchange for GGG and Neo-NFT trading.', long: 'G3DEX is the built-in trading platform where members can swap GGG, trade Neo-NFTs, manage escrow for commodities, and interact with gold-backed digital assets.', category: 'economy' },
  { term: 'Gaia Global Treasury', short: 'Transparent regulatory framework for verified collateral and global asset reconciliation.', long: 'The Gaia Global Treasury provides the institutional backbone for the GGG token ecosystem, ensuring proper collateralization, audit trails, and regulatory compliance for all treasury operations.', category: 'economy' },

  // Ultranet
  { term: 'Ultranet', short: 'Next-generation 6G communications infrastructure for sovereign digital society.', long: 'The Ultranet is a visionary project describing the next evolution of global communications — a 6G-class sovereign digital infrastructure integrating blockchain, advanced security protocols, mesh networking, and quantum-resistant encryption. It aims to provide humanity with censorship-resistant, decentralized connectivity that operates beyond the control of any single entity.\n\nKey pillars include:\n• 6G-class mesh networking with global satellite coverage\n• Blockchain-verified identity and transaction layers\n• Quantum-resistant end-to-end encryption\n• Decentralized governance via smart contracts\n• Integration with humanitarian and environmental monitoring systems\n\nThe Ultranet represents the technological foundation for a new era of digital sovereignty, aligning with the SaintAgent mission of conscious collaboration and freedom.', category: 'ultranet' },
  { term: 'Sovereign Digital Infrastructure', short: 'Technology stack owned by the people, not corporations.', long: 'Sovereign Digital Infrastructure refers to communication networks, data systems, and digital services that are collectively owned and governed by their users rather than centralized corporate or government entities. The Ultranet is the primary example.', category: 'ultranet' },
  { term: 'Mesh Networking', short: 'Peer-to-peer network topology without central servers.', long: 'Mesh networking allows devices to communicate directly with each other, forming a resilient web of connections. If one node goes down, traffic automatically routes through others. This is a core component of the Ultranet\'s censorship-resistant design.', category: 'ultranet' },
  { term: 'Quantum-Resistant Encryption', short: 'Cryptography designed to withstand quantum computer attacks.', long: 'As quantum computing advances, traditional encryption may become vulnerable. Quantum-resistant (post-quantum) cryptography uses mathematical problems that remain hard even for quantum computers, ensuring long-term data security within the Ultranet.', category: 'ultranet' },

  // Community
  { term: 'Circle', short: 'Interest or value-based community group.', long: 'Circles are themed groups where members gather around shared interests, values, or goals. Each Circle has its own feed, events, and discussions.', category: 'community' },
  { term: 'Mission', short: 'Collaborative task or quest with rewards.', long: 'Missions are structured collaborative activities with defined objectives, milestones, and GGG rewards. They can be created by leaders, the platform, or individual members.', category: 'community' },
  { term: 'Match', short: 'AI-suggested connection based on profile compatibility.', long: 'The matching engine analyzes skills, intentions, location, and values to suggest meaningful connections between members for collaboration, mentorship, or friendship.', category: 'community' },
  { term: 'Synchronicity Engine', short: 'Tool for sharing and discovering meaningful coincidences.', long: 'The Synchronicity Engine lets members log, share, and explore meaningful coincidences. AI analyzes patterns across the community to surface deeper connections.', category: 'community' },
  { term: 'Broadcast', short: 'Live podcast, webinar, or town hall event.', long: 'Broadcasts are scheduled live audio/video events hosted by community leaders. Members can RSVP, tune in live, or watch recordings afterward.', category: 'community' },
  { term: 'Leader Channel', short: 'Exclusive content and tools for verified 144K leaders.', long: 'The Leader Channel is a gated section for members who have achieved Verified 144K Leader status. It includes special missions, governance tools, and direct communication channels.', category: 'community' },

  // Spiritual & Mystical
  { term: 'Rank', short: 'Your progression level based on Reputation Points (RP).', long: 'Ranks progress from Seeker through Initiate, Adept, Practitioner, Master, Sage, Oracle, Ascended, and Guardian. Each rank unlocks new capabilities and recognition within the community.', category: 'spiritual' },
  { term: 'RP (Reputation Points)', short: 'Points earned through contributions that determine your rank.', long: 'Reputation Points are earned by completing missions, receiving endorsements, contributing to discussions, and other positive community actions. RP directly determines your rank progression.', category: 'spiritual' },
  { term: 'Initiation', short: 'Sacred pathway or activation ceremony within the platform.', long: 'Initiations are structured spiritual experiences available to members at certain rank levels. They include the 144K Activation and the 7th Seal Initiation.', category: 'spiritual' },
  { term: '144K Activation', short: 'Mass activation event for 144,000 lightworkers.', long: 'The 144K Activation is a platform-wide spiritual event aimed at activating 144,000 conscious individuals in alignment with ancient prophecy and modern purpose.', category: 'spiritual' },
  { term: 'Meta-Variance', short: 'The science of how reality adapts to you.', long: 'Meta-Variance is a concept within the quest system that adjusts difficulty, rewards, and narrative based on a coherence factor — representing how aligned a participant is with their mission purpose.', category: 'spiritual' },
  { term: 'Mystical Profile', short: 'Spiritual identity data including astrology, numerology, and more.', long: 'Your Mystical Profile includes your astrological signs (sun, moon, rising), numerology numbers (life path, destiny, soul urge), enneagram type, and destiny cards — used for deeper matching and self-discovery.', category: 'spiritual' },

  // Governance
  { term: 'Sovereign Alliance', short: 'Education and action framework for digital sovereignty.', long: 'The Sovereign Alliance is an educational hub and action framework teaching members about personal sovereignty, legal rights, and freedom-oriented governance principles.', category: 'governance' },
  { term: '144 Authority', short: 'Divine currency control and sacred mission governance body.', long: 'The 144 Authority oversees the sacred mission of the Gaia Global Treasury, ensuring that the platform\'s economic systems align with higher principles of fairness and transparency.', category: 'governance' },
  { term: 'Saint Steward', short: 'Nominated community guardian with elevated governance rights.', long: 'Saint Stewards are nominated by peers and verified by administrators. They serve as community moderators, dispute resolvers, and governance participants.', category: 'governance' },

  // Technology
  { term: 'Neo-NFT', short: 'Next-generation digital asset with provenance tracking.', long: 'Neo-NFTs are SaintAgent\'s advanced digital assets that include full provenance tracking, audit trails, document verification, and escrow capabilities — going beyond traditional NFTs.', category: 'technology' },
  { term: 'DRX (Digital Rights Exchange)', short: 'Marketplace for programmable digital asset rights.', long: 'The Digital Rights Exchange allows creators to license, rent, and monetize their content through programmable rights grants. It tracks usage and ensures fair compensation.', category: 'technology' },
  { term: 'Smart Contract', short: 'Self-executing code that enforces agreements on the blockchain.', long: 'Smart contracts are programs stored on a blockchain that automatically execute when predetermined conditions are met. They are used throughout the Ultranet and GGG ecosystem for trustless transactions.', category: 'technology' },
  { term: 'Blockchain', short: 'Distributed ledger technology for transparent, immutable record-keeping.', long: 'Blockchain is the underlying technology that ensures transparency and immutability in the GGG token system, Neo-NFT provenance, and Ultranet identity layers.', category: 'technology' },
];